### ISSUE TITLE
Allow ConsoleMenu to be used with .NET 4.0 apps

### ISSUE THREAD

**Issue by NickMRamirez** [EdwardSalter/ConsoleMenu#1]
Currently, if I try to pull in ConsoleMenu using nuget, such as:

```
Install-Package ConsoleMenu 
```

And my application targets .NET 4, I get the following error:

> Could not install package 'ConsoleMenu 0.1.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

This is because ConsoleMenu's target framework is version 4.5. 

However, I am able to compile ConsoleMenu after switching the version to 4.0.

Is there any reason that ConsoleMenu couldn't target a lower version of the .NET Framework? Such as 4.0? That'll allow it to be consumed by apps like mine and will also make it easier to release to servers that don't have .NET 4.5 installed.

**Comment by EdwardSalter** [comment]
> Is there any reason that ConsoleMenu couldn't target a lower version of the .NET Framework? Such as 4.0? That'll allow it to be consumed by apps like mine and will also make it easier to release to servers that don't have .NET 4.5 installed.

There is absolutely no reason for this project to be .NET 4.5 only. I think it was the just version I was using at the time and hadn't really thought about reducing the .NET version for compatibility.  
It is something that I will look at this evening or alternatively, I am open to a pull request if you find that the target framework can be reduced without major changes.
